// Complete system-field catalog for the legacy CRM forms. These fields are
// rendered by the existing form widgets; Form Builder controls their label,
// order, visibility and required state and appends custom fields separately.
module.exports = ({ field, options, required }) => {
  const f = (name, type, en, fa, extra = {}) => field(name, type, en, fa, en, extra);
  const choice = (name, en, fa, values, extra = {}) =>
    f(name, 'select', en, fa, { options: options(values), ...extra });
  const relation = (name, en, fa, moduleName, extra = {}) =>
    f(name, 'select', en, fa, { relation: moduleName, ...extra });
  const externalRelation = (name, en, fa, moduleName, extra = {}) =>
    relation(name, en, fa, moduleName, { external: true, ...extra });
  const multiRelation = (name, en, fa, moduleName, extra = {}) =>
    // Existing forms provide their own multi-record pickers. `text` prevents
    // the generic renderer from replacing those widgets with a single select.
    f(name, 'text', en, fa, { relation: moduleName, external: true, ...extra });

  return {
    Leads: [
      f('leadName', 'text', 'Lead Name', 'نام سرنخ', required),
      choice('leadStatus', 'Lead Status', 'وضعیت سرنخ', ['active', 'pending', 'sold']),
      f('leadEmail', 'email', 'Lead Email', 'ایمیل سرنخ', required),
      f('leadMobile', 'phone', 'Lead Mobile', 'موبایل سرنخ'),
      choice('leadCampaign', 'Lead Campaign', 'کمپین سرنخ', ['Referral', 'Online', 'Billboard', 'Activation', 'Agent']),
      choice('leadState', 'Lead State', 'مرحله سرنخ', ['Open', 'Parking', 'Waiting', 'Booked', 'Sealed']),
      choice('communicationTool', 'Communication Tool', 'روش ارتباط', ['WhatsApp', 'Email', 'Virtual Meet', 'Visit']),
      choice('listedFor', 'Listed For', 'نوع درخواست', ['Rent', 'Buy']),
      choice('propertyType', 'Property Type', 'نوع ملک', ['Apartment', 'Land', 'Manssonnate']),
      f('leadMessage', 'textarea', 'Lead Message', 'پیام سرنخ'),
      externalRelation('associatedListing', 'Associated Listing', 'ملک مرتبط', 'Properties'),
      externalRelation('contact', 'Converted Contact', 'مخاطب مرتبط', 'Contacts'),
      externalRelation('partnerCustomer', 'Partner Customer', 'مشتری همکار', 'Partner Customers'),
      multiRelation('relatedOpportunities', 'Related Opportunities', 'فرصت‌های مرتبط', 'Opportunities'),
      externalRelation('assignUser', 'Assigned User', 'کاربر مسئول', 'Users'),
    ],
    Contacts: [
      f('fullName', 'text', 'Full Name', 'نام کامل', required),
      f('email', 'email', 'Email', 'ایمیل', required),
      f('phoneNumber', 'phone', 'Phone Number', 'شماره تلفن', required),
      choice('campaign', 'Campaign', 'کمپین', ['Referral', 'Online', 'Billboard', 'Activation', 'Agent']),
      choice('state', 'State', 'مرحله', ['Open', 'Parking', 'Waiting', 'Booked', 'Sealed']),
      choice('communicationTool', 'Communication Tool', 'روش ارتباط', ['WhatsApp', 'Email', 'Virtual Meet', 'Visit']),
      choice('listedFor', 'Listed For', 'نوع درخواست', ['Rent', 'Buy']),
      f('message', 'textarea', 'Message', 'پیام'),
      multiRelation('interestProperty', 'Properties of Interest', 'املاک مورد علاقه', 'Properties'),
      multiRelation('quotes', 'Quotes', 'پیشنهادهای قیمت', 'Quotes'),
      multiRelation('relatedLeads', 'Related Leads', 'سرنخ‌های مرتبط', 'Leads'),
      multiRelation('relatedOpportunities', 'Related Opportunities', 'فرصت‌های مرتبط', 'Opportunities'),
      multiRelation('relatedProperties', 'Related Properties', 'املاک مرتبط', 'Properties'),
      relation('partnerCustomer', 'Partner Customer', 'مشتری همکار', 'Partner Customers'),
    ],
    Opportunities: [
      f('opportunityName', 'text', 'Opportunity Name', 'نام فرصت', required),
      relation('accountName', 'Partner Customer', 'مشتری همکار', 'Partner Customers'),
      relation('contact', 'Contact', 'مخاطب', 'Contacts'),
      relation('lead', 'Lead', 'سرنخ', 'Leads'),
      multiRelation('properties', 'Properties', 'املاک', 'Properties'),
      relation('assignUser', 'Assigned User', 'کاربر مسئول', 'Users'),
      choice('type', 'Opportunity Type', 'نوع فرصت', ['New Business', 'Existing Business']),
      choice('leadSource', 'Lead Source', 'منبع سرنخ', ['Cold Call', 'Existing Customer', 'Self Generated', 'Employee', 'Partner', 'Public Relations', 'Direct Mail', 'Conference', 'Trade Show', 'Website', 'Word of Mouth', 'Email', 'Other']),
      choice('currency', 'Currency', 'ارز', ['TRY', 'USD', 'EUR']),
      f('opportunityAmount', 'currency', 'Opportunity Amount', 'مبلغ فرصت', { min: 0 }),
      f('amount', 'currency', 'Amount', 'مبلغ', { min: 0 }),
      f('expectedCloseDate', 'date', 'Expected Close Date', 'تاریخ پیش‌بینی پایان'),
      f('nextStep', 'text', 'Next Step', 'اقدام بعدی'),
      choice('salesStage', 'Sales Stage', 'مرحله فروش', ['Prospecting', 'Qualification', 'Needs Analysis', 'Value Proposition', 'Identifying Decision Makers', 'Perception Analysis', 'Proposal/Price Quote', 'Negotiation/Review', 'Closed/Won', 'Closed/Lost']),
      f('probability', 'number', 'Probability (%)', 'احتمال موفقیت', { min: 0, max: 100 }),
      f('description', 'textarea', 'Description', 'توضیحات'),
    ],
    Tasks: [
      f('title', 'text', 'Title', 'عنوان', required),
      choice('category', 'Related Type', 'نوع ارتباط', ['None', 'Contact', 'Lead']),
      f('description', 'textarea', 'Description', 'توضیحات'),
      f('notes', 'textarea', 'Notes', 'یادداشت‌ها'),
      relation('assignTo', 'Contact', 'مخاطب', 'Contacts', { condition: { category: 'Contact' } }),
      relation('assignToLead', 'Lead', 'سرنخ', 'Leads', { condition: { category: 'Lead' } }),
      relation('assignedToUser', 'Assigned User', 'کاربر مسئول', 'Users'),
      relation('delegatedBy', 'Delegated By', 'واگذارکننده', 'Users'),
      f('reminder', 'text', 'Reminder', 'یادآور'),
      f('start', 'datetime', 'Start', 'زمان شروع', required),
      f('end', 'datetime', 'End', 'زمان پایان'),
      f('allDay', 'checkbox', 'All Day', 'تمام روز'),
      f('backgroundColor', 'text', 'Background Color', 'رنگ پس‌زمینه'),
      f('borderColor', 'text', 'Border Color', 'رنگ حاشیه'),
      f('textColor', 'text', 'Text Color', 'رنگ متن'),
      f('display', 'text', 'Display Mode', 'حالت نمایش'),
      f('url', 'url', 'Related URL', 'پیوند مرتبط'),
      choice('status', 'Status', 'وضعیت', ['todo', 'inProgress', 'pending', 'onHold', 'completed']),
    ],
    Meetings: [
      f('agenda', 'text', 'Agenda', 'موضوع جلسه', required),
      multiRelation('attendes', 'Contact Attendees', 'مخاطبان جلسه', 'Contacts'),
      multiRelation('attendesLead', 'Lead Attendees', 'سرنخ‌های جلسه', 'Leads'),
      choice('related', 'Related Type', 'نوع ارتباط', ['None', 'Contact', 'Lead']),
      f('location', 'text', 'Location', 'محل جلسه'),
      f('dateTime', 'datetime', 'Date and Time', 'تاریخ و ساعت', required),
      f('notes', 'textarea', 'Notes', 'یادداشت‌ها'),
    ],
    Calls: [
      relation('sender', 'Caller', 'تماس‌گیرنده', 'Users'),
      f('recipient', 'text', 'Recipient', 'مخاطب تماس', required),
      f('phoneNumber', 'phone', 'Phone Number', 'شماره تلفن'),
      f('callDuration', 'text', 'Call Duration', 'مدت تماس'),
      f('callNotes', 'textarea', 'Call Notes', 'یادداشت تماس'),
      f('startDate', 'datetime', 'Call Date', 'تاریخ تماس', required),
      relation('createByContact', 'Related Contact', 'مخاطب مرتبط', 'Contacts'),
      relation('createByLead', 'Related Lead', 'سرنخ مرتبط', 'Leads'),
      multiRelation('property', 'Related Properties', 'املاک مرتبط', 'Properties'),
      relation('salesAgent', 'Sales Agent', 'کارشناس فروش', 'Users'),
    ],
    Emails: [
      relation('sender', 'Sender', 'فرستنده', 'Users'),
      f('recipient', 'email', 'Recipient', 'گیرنده', required),
      f('subject', 'text', 'Subject', 'موضوع', required),
      choice('type', 'Email Type', 'نوع ایمیل', ['message', 'notification', 'follow-up', 'marketing']),
      f('message', 'textarea', 'Message', 'متن پیام'),
      f('html', 'textarea', 'HTML Content', 'محتوای HTML'),
      f('startDate', 'datetime', 'Send Date', 'تاریخ ارسال'),
      relation('createByContact', 'Related Contact', 'مخاطب مرتبط', 'Contacts'),
      relation('createByLead', 'Related Lead', 'سرنخ مرتبط', 'Leads'),
      multiRelation('property', 'Related Properties', 'املاک مرتبط', 'Properties'),
      relation('salesAgent', 'Sales Agent', 'کارشناس فروش', 'Users'),
    ],
    Invoices: [
      f('title', 'text', 'Title', 'عنوان', required),
      f('invoiceNumber', 'text', 'Invoice Number', 'شماره فاکتور'),
      f('quoteNumber', 'text', 'Quote Number', 'شماره پیشنهاد'),
      f('quoteDate', 'date', 'Quote Date', 'تاریخ پیشنهاد'),
      f('invoiceDate', 'date', 'Invoice Date', 'تاریخ فاکتور'),
      f('dueDate', 'date', 'Due Date', 'سررسید'),
      choice('status', 'Status', 'وضعیت', ['Draft', 'Sent', 'Pending', 'Partially Paid', 'Paid', 'Overdue', 'Cancelled']),
      choice('quoteStage', 'Quote Stage', 'مرحله پیشنهاد', ['Draft', 'Negotiation', 'Approved', 'Rejected']),
      relation('account', 'Partner Customer', 'مشتری همکار', 'Partner Customers'),
      relation('contact', 'Contact', 'مخاطب', 'Contacts'),
      relation('quotesId', 'Quote', 'پیشنهاد قیمت', 'Quotes'),
      relation('assignedTo', 'Assigned User', 'کاربر مسئول', 'Users'),
      f('description', 'textarea', 'Description', 'توضیحات'),
      ...['billing', 'shipping'].flatMap(prefix => [
        f(`${prefix}Street`, 'text', `${prefix} Street`, `${prefix === 'billing' ? 'خیابان صورتحساب' : 'خیابان ارسال'}`),
        f(`${prefix}City`, 'text', `${prefix} City`, `${prefix === 'billing' ? 'شهر صورتحساب' : 'شهر ارسال'}`),
        f(`${prefix}State`, 'text', `${prefix} State`, `${prefix === 'billing' ? 'استان صورتحساب' : 'استان ارسال'}`),
        f(`${prefix}PostalCode`, 'text', `${prefix} Postal Code`, `${prefix === 'billing' ? 'کدپستی صورتحساب' : 'کدپستی ارسال'}`),
        f(`${prefix}Country`, 'text', `${prefix} Country`, `${prefix === 'billing' ? 'کشور صورتحساب' : 'کشور ارسال'}`),
      ]),
      choice('currency', 'Currency', 'ارز', ['TRY', 'USD', 'EUR']),
      ...['subtotal', 'discount', 'tax', 'ptax', 'shipping', 'shippingTax', 'total', 'grandTotal'].map(name =>
        f(name, 'currency', name.replace(/([a-z])([A-Z])/g, '$1 $2'), name, { min: 0 })),
      choice('discountType', 'Discount Type', 'نوع تخفیف', ['none', 'Percentage', 'Fixed']),
      f('paymentTerms', 'text', 'Payment Terms', 'شرایط پرداخت'),
      f('approvalStatus', 'text', 'Approval Status', 'وضعیت تأیید'),
      f('invoiceStatus', 'text', 'Invoice Status', 'وضعیت فاکتور'),
      f('isCheck', 'checkbox', 'Confirmed', 'تأیید شده'),
      f('lineItems', 'textarea', 'Line Items', 'اقلام فاکتور'),
      f('items', 'textarea', 'Items', 'آیتم‌ها'),
    ],
    Quotes: [
      relation('lead', 'Lead', 'سرنخ', 'Leads'),
      relation('contact', 'Contact', 'مخاطب', 'Contacts'),
      relation('property', 'Property', 'ملک', 'Properties'),
      f('category', 'text', 'Category', 'دسته‌بندی'),
      f('accountName', 'text', 'Account Name', 'نام حساب'),
      f('accountNumber', 'number', 'Account Number', 'شماره حساب'),
      f('swiftCode', 'text', 'SWIFT Code', 'کد سوئیفت'),
      f('bank', 'text', 'Bank', 'بانک'),
      f('branch', 'text', 'Branch', 'شعبه'),
      f('amount', 'currency', 'Amount', 'مبلغ', { min: 0 }),
      f('unitPrice', 'currency', 'Unit Price', 'قیمت واحد', { min: 0 }),
      f('installments', 'textarea', 'Installments', 'اقساط'),
      f('description', 'textarea', 'Description', 'توضیحات'),
      f('salesManagerSign', 'text', 'Sales Manager Signature', 'امضای مدیر فروش'),
      f('buyerImage', 'file', 'Buyer Image', 'تصویر خریدار'),
    ],
    'Opportunity Project': [
      f('name', 'text', 'Name', 'نام پروژه', required),
      f('requirement', 'textarea', 'Requirement', 'نیازمندی', required),
      choice('category', 'Related Type', 'نوع ارتباط', ['None', 'Contact', 'Lead']),
      multiRelation('property', 'Properties', 'املاک', 'Properties'),
      relation('contact', 'Contact', 'مخاطب', 'Contacts', { condition: { category: 'Contact' } }),
      relation('lead', 'Lead', 'سرنخ', 'Leads', { condition: { category: 'Lead' } }),
    ],
    'Bank Details': [
      f('accountName', 'text', 'Account Name', 'نام صاحب حساب', required),
      f('accountNumber', 'number', 'Account Number', 'شماره حساب', required),
      f('swiftCode', 'text', 'SWIFT Code', 'کد سوئیفت'),
      f('bank', 'text', 'Bank', 'نام بانک', required),
      f('branch', 'text', 'Branch', 'شعبه'),
    ],
    Documents: [
      f('folderName', 'text', 'Folder Name', 'نام پوشه', required),
      relation('parentFolder', 'Parent Folder', 'پوشه والد', 'Documents'),
      f('file', 'file', 'Files', 'فایل‌ها'),
    ],
    Users: [
      f('firstName', 'text', 'First Name', 'نام', required),
      f('lastName', 'text', 'Last Name', 'نام خانوادگی', required),
      f('username', 'email', 'Email / Username', 'ایمیل / نام کاربری', required),
      f('phoneNumber', 'phone', 'Phone Number', 'شماره تلفن'),
      choice('role', 'Role', 'نقش', ['admin', 'user'], required),
    ],
    'Email Template': [
      f('templateName', 'text', 'Template Name', 'نام قالب', required),
      f('description', 'textarea', 'Description', 'توضیحات'),
      f('html', 'textarea', 'HTML Content', 'محتوای HTML'),
      f('design', 'textarea', 'Editor Design', 'طراحی ویرایشگر'),
    ],
  };
};
