const { test } = require('node:test');
const assert = require('node:assert/strict');
const mongoose = require('mongoose');
const express = require('express');
const jwt = require('jsonwebtoken');
const crypto = require('crypto');
const { jwtSecret } = require('../config/auth');
require('dotenv').config();
const enabled = process.env.ESTATE_INTEGRATION === '1';
test('authenticated estate CRUD, role permissions, definitions, relations and files', { skip: !enabled }, async () => {
  const dbName = `crm_estate_test_${crypto.randomUUID().replace(/-/g, '')}`;
  let server;
  await mongoose.connect(process.env.TEST_MONGO_URL || process.env.DB_URL || 'mongodb://127.0.0.1:27017', { dbName, serverSelectionTimeoutMS: 5000 });
  try {
    const app = express(); app.use(express.json()); app.use('/api', require('../controllers/route'));
    server = await new Promise(resolve => { const instance = app.listen(0, '127.0.0.1', () => resolve(instance)); });
    const base = `http://127.0.0.1:${server.address().port}/api`;
    const User = require('../model/schema/user');
    const admin = await User.create({ username: 'integration-admin', password: 'unused-test-hash', role: 'superAdmin' });
    const user = await User.create({ username: 'integration-user', password: 'unused-test-hash', role: 'user' });
    const token = actor => jwt.sign({ userId: actor._id }, jwtSecret);
    const api = async (method, route, body, actor = admin) => {
      const response = await fetch(base + route, { method, headers: { 'Content-Type': 'application/json', ...(actor ? { Authorization: token(actor) } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
      return { status: response.status, data: await response.json() };
    };
    assert.equal((await api('GET', '/estate/Properties', null, null)).status, 401);
    assert.equal((await api('GET', '/estate/Properties', null, user)).status, 403);
    const residence = await api('POST', '/estate/Residences', { name: 'Integration Residence', district: 'District' });
    assert.equal(residence.status, 201, JSON.stringify(residence));
    const partner = await api('POST', '/estate/Partner%20Customers', { customerType: 'COMPANY', companyName: 'Integration Company', phone: '+905551112233', status: 'ACTIVE', createBy: user._id });
    assert.equal(partner.status, 201, JSON.stringify(partner)); assert.equal(partner.data.createBy, String(admin._id));
    const definition = await api('GET', '/estate/definitions/Properties');
    const field = { name: 'field_reference', kind: 'CUSTOM_FIELD', type: 'text', enabled: true, required: true, label: { en: 'Reference', fa: 'مرجع', tr: 'Referans' } };
    const updated = await api('PUT', '/estate/definitions/Properties', { ...definition.data, fields: [...definition.data.fields, field] });
    assert.equal(updated.status, 200, JSON.stringify(updated));
    assert.equal((await api('PUT', '/estate/definitions/Properties', updated.data, user)).status, 403);
    const payload = { title: 'Integration Property', category: 'RESIDENTIAL', subtype: 'VILLA', transactionType: 'SALE', price: { amount: 1500000, currency: 'TRY' }, area: { value: 120, type: 'NET' }, isInsideResidence: true, residence: residence.data._id, sale: { status: 'SOLD', buyerType: 'PARTNER_CUSTOMER', partnerCustomer: partner.data._id } };
    assert.equal((await api('POST', '/estate/Properties', payload)).status, 400);
    payload.customFields = { field_reference: 'REF-1' };
    const property = await api('POST', '/estate/Properties', payload);
    assert.equal(property.status, 201, JSON.stringify(property));
    assert.equal(property.data.sale.partnerCustomer, partner.data._id);
    assert.equal((await api('DELETE', `/estate/Partner%20Customers/${partner.data._id}`)).status, 409);
    assert.equal((await api('POST', '/estate/Properties', { ...payload, residence: String(new mongoose.Types.ObjectId()) })).status, 400);
    const cleared = await api('PUT', `/estate/Properties/${property.data._id}`, { isInsideResidence: false, sale: { status: 'AVAILABLE' }, category: 'COMMERCIAL', subtype: 'SHOP', bedroom: '1+1' });
    assert.equal(cleared.status, 200, JSON.stringify(cleared)); assert.equal(cleared.data.residence, null); assert.equal(cleared.data.sale.partnerCustomer, null); assert.equal(cleared.data.bedroom, null);
    const list = await api('GET', '/estate/Properties?category=COMMERCIAL&priceMin=100&limit=1');
    assert.equal(list.data.total, 1); assert.equal(list.data.items.length, 1);
    assert.equal((await api('GET', '/estate/Properties/not-an-id')).status, 400);
    const form = new FormData(); form.append('files', new Blob(['integration test'], { type: 'text/plain' }), 'integration.txt');
    const upload = await fetch(base + '/estate/files', { method: 'POST', headers: { Authorization: token(admin) }, body: form });
    assert.equal(upload.status, 201); const files = await upload.json(); assert.ok(files[0].uploadedAt);
    assert.equal((await api('PUT', `/estate/Properties/${property.data._id}`, { files })).status, 200);
    assert.equal((await api('PUT', `/estate/Properties/${property.data._id}`, { description: 'keeps stored file metadata' })).status, 200);
    const download = await fetch(`${base}/estate/files/${files[0].id}`, { headers: { Authorization: token(admin) } });
    assert.equal(await download.text(), 'integration test');
    assert.equal((await api('DELETE', `/estate/Properties/${property.data._id}`)).status, 200);
    assert.equal((await api('GET', '/estate/Properties')).data.total, 0);
    assert.equal((await api('GET', `/estate/Properties/${property.data._id}`, null, user)).status, 403);
    const storedFiles = await mongoose.model('EstateFile').find().lean();
    const fs = require('fs'); const path = require('path');
    for (const file of storedFiles) await fs.promises.unlink(path.resolve(__dirname, '../uploads/estate', file.storageName));
  } finally {
    if (server) await new Promise(resolve => server.close(resolve));
    if (mongoose.connection.name !== dbName || !dbName.startsWith('crm_estate_test_')) throw new Error('Unexpected integration database');
    await mongoose.connection.dropDatabase();
    await mongoose.disconnect();
  }
});
